#!/bin/bash
# 🚀 PRODUCTION DEPLOYMENT QUICK START
# 
# This script provides a quick reference for deploying to production
# Save as: DEPLOY_NOW.sh or reference manually

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         🚀 PRODUCTION DEPLOYMENT - QUICK START                ║"
echo "║              Status: READY FOR DEPLOYMENT ✅                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: GENERATE PRODUCTION SECRETS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run:"
echo "  cd backend"
echo "  node scripts/generate-secrets.js"
echo ""
echo "✓ Copy the output to .env file"
echo ""

echo "📋 STEP 2: UPDATE ENVIRONMENT CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Edit .env file:"
echo "  DB_PASSWORD=<secure_password>"
echo "  JWT_SECRET=<from_generate-secrets.js>"
echo "  CORS_ORIGIN=https://yourdomain.com"
echo "  BACKEND_URL=https://api.yourdomain.com"
echo "  FRONTEND_URL=https://yourdomain.com"
echo ""

echo "📋 STEP 3: UPDATE API ENDPOINT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Edit: frontend/lib/services/api_service.dart"
echo ""
echo "  OLD: static const String baseUrl = 'http://localhost:3001';"
echo "  NEW: static const String baseUrl = 'https://api.yourdomain.com';"
echo ""

echo "📋 STEP 4: CHOOSE YOUR DEPLOYMENT PLATFORM"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "RECOMMENDED: RENDER ($7/mo)"
echo "  1. Go to https://render.com"
echo "  2. Connect GitHub or upload files"
echo "  3. Create Web Service for backend"
echo "  4. Create Static Site for frontend"
echo "  5. Add environment variables from .env"
echo "  ⏱️  Time: ~5 minutes"
echo ""

echo "ALTERNATIVE: VERCEL (Frontend) + RENDER (Backend)"
echo "  Frontend:"
echo "    vercel --prod"
echo "  Backend: (use Render)"
echo "  ⏱️  Time: ~3 minutes frontend + 5 minutes backend"
echo ""

echo "ALTERNATIVE: FIREBASE"
echo "  firebase deploy --only hosting,functions"
echo "  ⏱️  Time: ~10 minutes"
echo ""

echo "📋 STEP 5: VERIFY DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test backend:"
echo "  curl https://api.yourdomain.com/api/auth/me"
echo ""
echo "Test frontend:"
echo "  curl https://yourdomain.com"
echo ""
echo "Test OCR endpoint:"
echo "  curl -X POST https://api.yourdomain.com/api/ocr/verify \\\\"
echo "    -H 'Authorization: Bearer YOUR_TOKEN' \\\\"
echo "    -H 'Content-Type: application/json' \\\\"
echo "    -d '{\"userData\":{\"nom\":\"TEST\"},\"ocrData\":{\"nom\":\"TEST\"}}'"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  📚 For detailed information, see:                            ║"
echo "║     - DEPLOYMENT_CHECKLIST_FINAL.md                          ║"
echo "║     - QUICK_DEPLOYMENT_GUIDE.md                              ║"
echo "║     - API_ENDPOINT_CONFIGURATION.md                          ║"
echo "║     - DEPLOYMENT_SESSION_COMPLETE.md                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Ready to deploy! Follow the steps above."
echo ""
